# Generated by Django 4.2.2 on 2023-06-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_bookmarks_current_alter_bookmarks_latest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='bookmarks',
            old_name='read_status_id',
            new_name='read_status',
        ),
        migrations.RenameField(
            model_name='bookmarks',
            old_name='status_id',
            new_name='status',
        ),
    ]
