# Generated by Django 4.2.2 on 2023-06-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_category_id_bookmarks_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readstatuses',
            name='icon',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='statuses',
            name='icon',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
