# Generated by Django 4.2.2 on 2023-06-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_readstatuses_icon_alter_statuses_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readstatuses',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='statuses',
            name='icon',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
