# Generated by Django 4.2.2 on 2023-06-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_readstatuses_icon_alter_statuses_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='link',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
    ]
