# Generated by Django 4.2.2 on 2023-06-07 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_bookmarks_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='read_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='base.readstatuses'),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='base.statuses'),
        ),
    ]
